kotlin.code.style=official

# Plugin versions
kotlinterVersion=5.7.0

# Eksterne avhengigheter
brregClientVersion=0.8.1
dokarkivClientVersion=1.0.0
gcpStorageVersion=2.48.1
kafkaVersion=3.9.2
kotestVersion=6.0.4
kotlinVersion=2.3.21
ktorVersion=3.5.2
logbackEncoderVersion=9.0
logbackVersion=1.5.37
mockkVersion=1.14.11
pdlClientVersion=0.9.0
utilsVersion=0.10.1
