apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: helsearbeidsgiver
  name: refusjon
  namespace: helsearbeidsgiver
spec:
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: "50m"
      memory: "512Mi"
    limits:
      memory: "1024Mi"
  observability:
    logging:
      destinations:
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  liveness:
    failureThreshold: 5
    initialDelay: 15
    path: /health/is-alive
    periodSeconds: 10
    timeout: 1
  readiness:
    failureThreshold: 5
    initialDelay: 15
    path: /health/is-ready
    periodSeconds: 10
    timeout: 1
  accessPolicy:
    inbound:
      rules:
        - application: sykepenger-im-lps-api
    outbound:
      rules:
        - application: helsearbeidsgiver-pdfgen
        - application: logging
          namespace: nais-system
      external:
        - host: data.brreg.no
  azure:
    application:
      enabled: true
  env:
    - name: BRREG_URL
      value: "https://data.brreg.no/enhetsregisteret/api/underenheter"
    - name: KAFKA_TOPIC_REFUSJON
      value: helsearbeidsgiver.refusjon
    - name: PDFGEN_REFUSJON_URL
      value: "http://helsearbeidsgiver-pdfgen/api/v1/genpdf/refusjon/refusjon"
